jenkins:
  systemMessage: "Hello! Welcome to my Jenkins instance :)"
  
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "d7ca8583d81d46b1b26a68e5b5e721a0"
        - id: "jigglypuff"
          password: "jigglypuff"

jobs:
  - file: /var/jenkins_home/casc_configs/job_dsl.groovy
